/* -----------------------------------------------------------------------------
 * Error codes (generated).
 * -----------------------------------------------------------------------------
 */

#ifndef INC_ERRORCODE
#define INC_ERRORCODE

#ifdef __cplusplus
extern "C"
{
#endif

#define EFB_OK 0
#define EFBERR_FLOW 1
#define EFBERR_SECURITY 2
#define EFBERR_TEMP_GENE 3
#define EFBERR_ISOLATION 5
#define EFBERR_IGBT 8
#define EFBERR_DURATION 9
#define EFBERR_RESISTIVITY 10
#define EFBERR_ACTIVE_CB 16
#define EFBERR_TIMEOUT_EOC 17
#define EFBERR_INACTIVE_CB 18
#define EFBERR_CONFIG_PULSES 20
#define EFBERR_CONFIG_T_ON 21
#define EFBERR_CONFIG_COST 23
#define EFBERR_UNKN_KEY 25
#define EFBERR_TIRBACK_PRE 27
#define EFBERR_TIRBACK_ON 28
#define EFBERR_TIRBACK_OFF 29
#define EFBERR_TIRBACK_POST 30
#define EFBERR_ABNORMAL_CB 31
#define EFBERR_COM_UART 32
#define EFBERR_COM_ACK 33
#define EFBERR_COM_CHK 34
#define EFBERR_COM_TIMEOUT_ACK 35
#define EFBERR_COM_UART_FE 36
#define EFBERR_COM_UART_PE 37
#define EFBERR_COM_UART_DOR 38
#define EFBERR_COM_HEADER 42
#define EFBERR_COM_DATA 43
#define EFBERR_COM_QUEUE 44
#define EFBERR_COM_TIMEOUT_RX 45
#define EFBERR_COM_UNKN_CMD 46
#define EFBERR_COM_RX 47
#define EFBERR_CONFIG_SETPOINT 64
#define EFBERR_CONFIG_T_ON_TOTAL 65
#define EFBERR_POWER 67
#define EFBERR_I2C 68
#define EFBERR_DRIFT_COEFF 69
#define EFBERR_DRIFT_COEFF_2 70
#define EFBERR_FLOW_CARD 71
#define EFBERR_SPI_AVAIL 72
#define EFBERR_SPI_COMM 73
#define EFBERR_COUNTER 74
#define EFBERR_COUNTER_REAL 75
#define EFBERR_RTC_UNSUPPORTED_API 76


#define EFBERR_BUG 13
#define EFBERR_BADCALL 14
#define EFBERR_BADARGS 15
#define EFBERR_INSUFFICIENT_HEAP_SPACE 50
#define EFBERR_TASK_CREATION_FAIL 51
#define EFBERR_I2C_COMM 90
#define EFBERR_UART_COMM 91
#define EFBERR_MEMSET 100
#define EFBERR_MEMCPY 101
#define EFBERR_USPRINTF_WRONG_FLAG 150
#define EFBERR_BUFFER_OVERFLOW 200
#define EFBERR_BUFFER_CLOSED 201
#define EFBERR_BUFFER_NOT_CLOSED 202
#define EFBERR_BUFFER_EMPTY 203
#define EFBERR_BUFFER_NOT_ENOUGH_DATA 204
#define EFBERR_AES_FRAME_OVERFLOW 205
#define EFBERR_AES_FRAME_NOT_BUILT 206
#define EFBERR_FORMAT_MALFORMED_DATETIME 500
#define EFBERR_UART0_RXBUFFER_OVERFLOW 1000
#define EFBERR_UART0_FRAME 1001
#define EFBERR_UART0_DATA_OVERRUN 1002
#define EFBERR_UART0_RXBUFFER_EMPTY 1003
#define EFBERR_UART1_RXBUFFER_OVERFLOW 1004
#define EFBERR_UART1_FRAME 1005
#define EFBERR_UART1_DATA_OVERRUN 1006
#define EFBERR_UART1_RXBUFFER_EMPTY 1007
#define EFBERR_UART2_RXBUFFER_OVERFLOW 1008
#define EFBERR_UART2_FRAME 1009
#define EFBERR_UART2_DATA_OVERRUN 1010
#define EFBERR_UART2_RXBUFFER_EMPTY 1011
#define EFBERR_UART3_RXBUFFER_OVERFLOW 1012
#define EFBERR_UART3_FRAME 1013
#define EFBERR_UART3_DATA_OVERRUN 1014
#define EFBERR_UART3_RXBUFFER_EMPTY 1015
#define EFBERR_I2C_LECTURE 1100
#define EFBERR_I2C_ECRITURE 1101
#define EFBERR_I2C_MUTEX 1102
#define EFBERR_SPI_FRAME_INVALID 1200
#define EFBERR_SPI_FRAME_INVALID_SIZE 1201
#define EFBERR_UART_BUFFER_EMPTY 900
#define EFBERR_UART_BUFFER_FULL 901
#define EFBERR_UART0_BUSY 902
#define EFBERR_UART1_BUSY 903
#define EFBERR_UART2_BUSY 904
#define EFBERR_UART3_BUSY 905
#define EFBERR_UART0_ACK_FAIL 906
#define EFBERR_UART0_NO_ACK 907
#define EFBERR_UART0_REP_FAIL 908
#define EFBERR_UART0_NO_REP 909
#define EFBERR_UART1_REP_FAIL2 911
#define EFBERR_UART1_REP_FAIL 912
#define EFBERR_UART1_NO_REP 913
#define EFBERR_UART2_ACK_FAIL 914
#define EFBERR_UART2_NO_ACK 915
#define EFBERR_UART2_REP_FAIL 916
#define EFBERR_UART2_NO_REP 917
#define EFBERR_UART3_ACK_FAIL 918
#define EFBERR_UART3_NO_ACK 919
#define EFBERR_UART3_REP_FAIL 920
#define EFBERR_UART3_NO_REP 921
#define EFBERR_TIMER_DEAMON_UNAVAILABLE 950
#define EFBERR_SEMAPHORE_TAKE 1500
#define EFBERR_SEMAPHORE_GIVE 1501
#define EFBERR_QUEUE_FULL 1502
#define EFBERR_QUEUE_EMPTY 1503
#define EFBERR_TIMEOUT_PAM_TRIGGER 2000
#define EFBERR_STOP_FIRING 2001

/* -----------------------------------------------------------------------------
 */
#ifdef __cplusplus
}
#endif
#endif /* INC_ERRORCODE */